version: 2

builds:
  - main: ./cmd/alfred
    binary: alfred
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "alfred_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
