/**
 * AGENTS.md generator. Writes the qult workflow block as a marked region
 * (`<!-- @generated by qult -->` ... `<!-- /@generated -->`) so subsequent
 * `qult update` runs can refresh just the block while preserving any
 * user-authored content surrounding it.
 *
 * Idempotent:
 *  - new file → write header + marker block.
 *  - existing file with marker block → replace the block content.
 *  - existing file without marker block → append the block at the end.
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { atomicWriteAt } from "./fs.ts";

const MARKER_BEGIN_RE = /<!-- @generated by qult[^>]*-->/;
const MARKER_END = "<!-- /@generated -->";

export interface AgentsMdOptions {
	projectRoot: string;
	templateRoot: string;
	qultVersion: string;
}

/** Read the bundled constitution.md and wrap it in the @generated marker block. */
function buildBlock(templateRoot: string, qultVersion: string): string {
	const constitution = readFileSync(join(templateRoot, "constitution.md"), "utf8").trimEnd();
	return [
		`<!-- @generated by qult v${qultVersion} — DO NOT EDIT THIS SECTION -->`,
		constitution,
		MARKER_END,
		"",
	].join("\n");
}

/**
 * Replace the existing marker block, or append a new one if missing.
 * Returns the updated file contents (does not write).
 */
export function injectBlock(existing: string, block: string): string {
	const beginMatch = existing.match(MARKER_BEGIN_RE);
	if (!beginMatch || beginMatch.index === undefined) {
		const sep = existing.endsWith("\n") ? "\n" : "\n\n";
		return `${existing}${sep}${block}`;
	}
	const begin = beginMatch.index;
	const endIdx = existing.indexOf(MARKER_END, begin);
	if (endIdx === -1) {
		// Truncated marker — replace from begin to EOF.
		return `${existing.slice(0, begin)}${block}`;
	}
	const after = existing.slice(endIdx + MARKER_END.length);
	return `${existing.slice(0, begin)}${block.trimEnd()}${after}`;
}

/** Write or update AGENTS.md in `projectRoot`. */
export async function writeAgentsMd(opts: AgentsMdOptions): Promise<void> {
	const path = join(opts.projectRoot, "AGENTS.md");
	const block = buildBlock(opts.templateRoot, opts.qultVersion);
	if (!existsSync(path)) {
		atomicWriteAt(path, `# AGENTS.md\n\n${block}`);
		return;
	}
	const existing = readFileSync(path, "utf8");
	atomicWriteAt(path, injectBlock(existing, block));
}
