/**
 * AGENTS.md generator. Writes the qult workflow block as a marked region
 * (`<!-- @generated by qult -->` ... `<!-- /@generated -->`) so subsequent
 * `qult update` runs can refresh just the block while preserving any
 * user-authored content surrounding it.
 *
 * Idempotent:
 *  - new file → write header + marker block.
 *  - existing file with marker block → replace the block content.
 *  - existing file without marker block → append the block at the end.
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { atomicWriteAt } from "./fs.ts";

const MARKER_BEGIN_RE = /<!-- @generated by qult[^>]*-->/g;
const MARKER_END = "<!-- /@generated -->";

export interface AgentsMdOptions {
	projectRoot: string;
	templateRoot: string;
	qultVersion: string;
}

/** Read the bundled constitution.md and wrap it in the @generated marker block. */
function buildBlock(templateRoot: string, qultVersion: string): string {
	const constitution = readFileSync(join(templateRoot, "constitution.md"), "utf8").trimEnd();
	return [
		`<!-- @generated by qult v${qultVersion} — DO NOT EDIT THIS SECTION -->`,
		constitution,
		MARKER_END,
		"",
	].join("\n");
}

/**
 * Replace the existing marker block(s), or append a new one if missing.
 * Returns the updated file contents (does not write).
 *
 * Behavior on multiple `@generated by qult` blocks (corrupted state from a
 * prior partial write or hand-edit): collapse all of them into the new one
 * placed at the position of the first match. This keeps AGENTS.md a
 * single-source-of-truth even when concurrent runs leave duplicates.
 */
export function injectBlock(existing: string, block: string): string {
	const allBegins = [...existing.matchAll(MARKER_BEGIN_RE)];
	if (allBegins.length === 0) {
		const sep = existing.endsWith("\n") ? "\n" : "\n\n";
		return `${existing}${sep}${block}`;
	}
	let result = existing;
	// Iterate in reverse so earlier indices stay valid as we slice.
	for (let i = allBegins.length - 1; i >= 0; i--) {
		const m = allBegins[i];
		if (!m || m.index === undefined) continue;
		const begin = m.index;
		const endIdx = result.indexOf(MARKER_END, begin);
		if (endIdx === -1) {
			// Truncated marker — replace from begin to EOF.
			result = result.slice(0, begin);
			continue;
		}
		const after = result.slice(endIdx + MARKER_END.length);
		// Replacement: leave only the first block; for later duplicates, drop them entirely.
		const replacement = i === 0 ? block.trimEnd() : "";
		result = `${result.slice(0, begin)}${replacement}${after}`;
	}
	return result;
}

/** Write or update AGENTS.md in `projectRoot`. */
export async function writeAgentsMd(opts: AgentsMdOptions): Promise<void> {
	const path = join(opts.projectRoot, "AGENTS.md");
	const block = buildBlock(opts.templateRoot, opts.qultVersion);
	if (!existsSync(path)) {
		atomicWriteAt(path, `# AGENTS.md\n\n${block}`);
		return;
	}
	const existing = readFileSync(path, "utf8");
	atomicWriteAt(path, injectBlock(existing, block));
}
