import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { injectBlock, writeAgentsMd } from "../../templates/agents-md.ts";

const TEMPLATE_ROOT = resolve(__dirname, "../../templates/bundled");

let projectRoot: string;

beforeEach(() => {
	projectRoot = mkdtempSync(join(tmpdir(), "qult-agents-md-"));
});
afterEach(() => {
	rmSync(projectRoot, { recursive: true, force: true });
});

describe("injectBlock", () => {
	it("appends a new block when no marker exists", () => {
		const block = "<!-- @generated by qult vX -->\nbody\n<!-- /@generated -->\n";
		const result = injectBlock("# user content\n", block);
		expect(result.endsWith("<!-- /@generated -->\n")).toBe(true);
		expect(result.startsWith("# user content")).toBe(true);
	});

	it("replaces an existing marker block in place, preserving surrounding text", () => {
		const before =
			"# top\n\n<!-- @generated by qult vOLD -->\nold\n<!-- /@generated -->\n\n# bottom\n";
		const block = "<!-- @generated by qult vNEW -->\nnew body\n<!-- /@generated -->\n";
		const result = injectBlock(before, block);
		expect(result).toContain("# top");
		expect(result).toContain("# bottom");
		expect(result).toContain("new body");
		expect(result).not.toContain("old");
	});

	it("collapses multiple @generated blocks into one (corrupted state recovery)", () => {
		const before =
			"# top\n\n<!-- @generated by qult v1 -->\nfirst\n<!-- /@generated -->\n\n<!-- @generated by qult v2 -->\nsecond\n<!-- /@generated -->\n";
		const block = "<!-- @generated by qult vNEW -->\nnew body\n<!-- /@generated -->\n";
		const result = injectBlock(before, block);
		expect((result.match(/@generated by qult/g) ?? []).length).toBe(1);
		expect(result).toContain("new body");
		expect(result).not.toContain("first");
		expect(result).not.toContain("second");
	});
});

describe("writeAgentsMd", () => {
	it("creates AGENTS.md with header + block when missing", async () => {
		await writeAgentsMd({ projectRoot, templateRoot: TEMPLATE_ROOT, qultVersion: "1.1.0" });
		const text = readFileSync(join(projectRoot, "AGENTS.md"), "utf8");
		expect(text).toContain("# AGENTS.md");
		expect(text).toContain("@generated by qult v1.1.0");
		expect(text).toContain("qult Workflow");
	});

	it("preserves existing user content when updating", async () => {
		writeFileSync(join(projectRoot, "AGENTS.md"), "# AGENTS.md\n\n## user note\nkeep me\n");
		await writeAgentsMd({ projectRoot, templateRoot: TEMPLATE_ROOT, qultVersion: "1.1.0" });
		const text = readFileSync(join(projectRoot, "AGENTS.md"), "utf8");
		expect(text).toContain("## user note");
		expect(text).toContain("keep me");
		expect(text).toContain("@generated by qult v1.1.0");
	});

	it("is idempotent: two writes produce the same content", async () => {
		await writeAgentsMd({ projectRoot, templateRoot: TEMPLATE_ROOT, qultVersion: "1.1.0" });
		const first = readFileSync(join(projectRoot, "AGENTS.md"), "utf8");
		await writeAgentsMd({ projectRoot, templateRoot: TEMPLATE_ROOT, qultVersion: "1.1.0" });
		const second = readFileSync(join(projectRoot, "AGENTS.md"), "utf8");
		expect(second).toBe(first);
	});
});
