package hookhandler

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/hir4ta/claude-buddy/internal/store"
)

// persistSessionMemory writes learned knowledge to Claude Code's memory directory
// so it auto-loads every session. Called at the end of persistSessionData().
// All errors go to stderr; this function never blocks SessionEnd.
func persistSessionMemory(sessionID, cwd string) {
	if cwd == "" {
		return
	}

	st, err := store.OpenDefaultCached()
	if err != nil {
		fmt.Fprintf(os.Stderr, "memory: open store: %v\n", err)
		return
	}

	// Skip if not enough sessions to produce useful knowledge.
	stats, err := st.GetProjectSessionStats(cwd)
	if err != nil || stats.TotalSessions < 3 {
		return
	}

	projectKey := deriveProjectKey(cwd)
	memDir := filepath.Join(homeDir(), ".claude", "projects", projectKey, "memory")
	if err := os.MkdirAll(memDir, 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "memory: mkdir %s: %v\n", memDir, err)
		return
	}

	content := generateMemoryContent(st, cwd, stats.TotalSessions)
	if content == "" {
		return
	}

	// Atomic write: write to .tmp, then rename.
	target := filepath.Join(memDir, "MEMORY.md")
	tmp := target + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "memory: write tmp: %v\n", err)
		return
	}
	if err := os.Rename(tmp, target); err != nil {
		fmt.Fprintf(os.Stderr, "memory: rename: %v\n", err)
		_ = os.Remove(tmp)
	}
}

// deriveProjectKey converts an absolute path to Claude Code's project key format.
// Example: /Users/user/Projects/claude-buddy -> -Users-user-Projects-claude-buddy
func deriveProjectKey(cwd string) string {
	return strings.ReplaceAll(cwd, "/", "-")
}

// generateMemoryContent builds the MEMORY.md content from store data.
// Returns empty string if there's nothing meaningful to write.
// Keeps output under 200 lines (Claude Code's memory file truncation limit).
func generateMemoryContent(st *store.Store, cwd string, totalSessions int) string {
	var b strings.Builder

	// Header.
	b.WriteString("# claude-buddy: Project Learning Notes\n\n")
	b.WriteString("> Auto-generated by claude-buddy. Do not edit manually.\n")
	fmt.Fprintf(&b, "> Last updated: %s | Sessions: %d\n", time.Now().UTC().Format(time.RFC3339), totalSessions)

	sections := 0

	// Common failures and solutions.
	if s := buildFailuresSection(st, cwd); s != "" {
		b.WriteString("\n")
		b.WriteString(s)
		sections++
	}

	// Important design decisions.
	if s := buildDecisionsSection(st, cwd); s != "" {
		b.WriteString("\n")
		b.WriteString(s)
		sections++
	}

	// File co-change patterns.
	if s := buildCoChangeSection(st); s != "" {
		b.WriteString("\n")
		b.WriteString(s)
		sections++
	}

	// Work style.
	if s := buildWorkStyleSection(st); s != "" {
		b.WriteString("\n")
		b.WriteString(s)
		sections++
	}

	if sections == 0 {
		return ""
	}

	// Enforce 200-line limit.
	result := b.String()
	lines := strings.Split(result, "\n")
	if len(lines) > 200 {
		lines = lines[:200]
		result = strings.Join(lines, "\n")
	}

	return result
}

// buildFailuresSection generates the "Common Failures and Solutions" section.
func buildFailuresSection(st *store.Store, cwd string) string {
	failures, err := st.FrequentFailures(cwd, 5)
	if err != nil || len(failures) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("## Common Failures and Solutions\n")

	for _, f := range failures {
		sig := f.ErrorSignature
		if len([]rune(sig)) > 60 {
			sig = string([]rune(sig)[:60])
		}

		// Look up solutions for resolution info.
		solutions, _ := st.SearchFailureSolutions(f.FailureType, f.ErrorSignature, 1)
		if len(solutions) > 0 && solutions[0].SolutionText != "" {
			sol := solutions[0]
			solutionText := sol.SolutionText
			if len([]rune(solutionText)) > 80 {
				solutionText = string([]rune(solutionText)[:80])
			}

			line := fmt.Sprintf("- `%s`", sig)
			if sol.TimesSurfaced > 0 {
				pct := 100 * sol.TimesEffective / sol.TimesSurfaced
				line += fmt.Sprintf(" -> %s (%d occurrences, %d%% resolved)", solutionText, f.Count, pct)
			} else {
				line += fmt.Sprintf(" -> %s (%d occurrences)", solutionText, f.Count)
			}
			b.WriteString(line + "\n")
		} else {
			fmt.Fprintf(&b, "- `%s` (%d occurrences)\n", sig, f.Count)
		}
	}

	return b.String()
}

// buildDecisionsSection generates the "Important Design Decisions" section.
func buildDecisionsSection(st *store.Store, cwd string) string {
	projectName := filepath.Base(cwd)
	decisions, err := st.GetDecisions("", projectName, 5)
	if err != nil || len(decisions) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("## Important Design Decisions\n")

	for _, d := range decisions {
		text := d.DecisionText
		if len([]rune(text)) > 120 {
			text = string([]rune(text)[:120])
		}

		if d.Topic != "" {
			topic := d.Topic
			if len([]rune(topic)) > 60 {
				topic = string([]rune(topic)[:60])
			}
			fmt.Fprintf(&b, "- %s (%s)\n", text, topic)
		} else {
			fmt.Fprintf(&b, "- %s\n", text)
		}
	}

	return b.String()
}

// buildCoChangeSection generates the "File Co-change Patterns" section.
func buildCoChangeSection(st *store.Store) string {
	pairs, err := st.TopCoChangePairs(3)
	if err != nil || len(pairs) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("## File Co-change Patterns\n")

	for _, cc := range pairs {
		a := shortenPath(cc.FileA)
		bPath := shortenPath(cc.FileB)
		fmt.Fprintf(&b, "- %s <-> %s (%d sessions)\n", a, bPath, cc.SessionCount)
	}

	return b.String()
}

// buildWorkStyleSection generates the "Work Style" section.
func buildWorkStyleSection(st *store.Store) string {
	cluster := st.UserCluster()

	tf, tfCount, _ := st.GetUserProfile("test_frequency")
	rw, rwCount, _ := st.GetUserProfile("read_write_ratio")

	// Need at least some data to be useful.
	if tfCount == 0 && rwCount == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("## Work Style\n")
	fmt.Fprintf(&b, "- Cluster: %s", cluster)
	if tfCount > 0 {
		fmt.Fprintf(&b, " | Test frequency: %.2f", tf)
	}
	if rwCount > 0 {
		fmt.Fprintf(&b, " | R/W ratio: %.1f", rw)
	}
	b.WriteString("\n")

	return b.String()
}

// shortenPath strips common prefixes to make file paths more readable.
// Converts absolute paths to relative-looking paths.
func shortenPath(p string) string {
	// Strip leading slashes and common home dir prefix for brevity.
	if idx := strings.Index(p, "/internal/"); idx >= 0 {
		return p[idx+1:]
	}
	if idx := strings.Index(p, "/src/"); idx >= 0 {
		return p[idx+1:]
	}
	if idx := strings.Index(p, "/pkg/"); idx >= 0 {
		return p[idx+1:]
	}
	// Use just the base filename and parent dir for readability.
	dir := filepath.Dir(p)
	base := filepath.Base(p)
	parent := filepath.Base(dir)
	if parent != "." && parent != "/" {
		return parent + "/" + base
	}
	return base
}

// homeDir returns the user's home directory, falling back to ".".
func homeDir() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return "."
	}
	return home
}
