/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksSlugRouteImport } from './routes/tasks.$slug'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksSlugRoute = TasksSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TasksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/knowledge': typeof KnowledgeRoute
  '/tasks': typeof TasksRouteWithChildren
  '/tasks/$slug': typeof TasksSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/knowledge': typeof KnowledgeRoute
  '/tasks': typeof TasksRouteWithChildren
  '/tasks/$slug': typeof TasksSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/knowledge': typeof KnowledgeRoute
  '/tasks': typeof TasksRouteWithChildren
  '/tasks/$slug': typeof TasksSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/activity' | '/knowledge' | '/tasks' | '/tasks/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/activity' | '/knowledge' | '/tasks' | '/tasks/$slug'
  id: '__root__' | '/' | '/activity' | '/knowledge' | '/tasks' | '/tasks/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  KnowledgeRoute: typeof KnowledgeRoute
  TasksRoute: typeof TasksRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$slug': {
      id: '/tasks/$slug'
      path: '/$slug'
      fullPath: '/tasks/$slug'
      preLoaderRoute: typeof TasksSlugRouteImport
      parentRoute: typeof TasksRoute
    }
  }
}

interface TasksRouteChildren {
  TasksSlugRoute: typeof TasksSlugRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksSlugRoute: TasksSlugRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  KnowledgeRoute: KnowledgeRoute,
  TasksRoute: TasksRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
